name: Build
on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Build Image
      run: docker build .